name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  repository_dispatch:
    types: [call]
    
jobs:
  run-on-dispatch:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # - name: Install Playwright Browsers
    #   run: npx playwright install --with-deps
    # - name: Run Playwright tests
    #   run: npx playwright test
    # - uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: playwright-report
    #     path: playwright-report/
    #     retention-days: 30

    # - name: Repository Dispatch
    #   run: |
    #     curl -X POST https://api.github.com/repos/go-bazzinga/hot-or-not-web-leptos-ssr-e2e-test/dispatches \
    #     -H 'Accept: application/vnd.github+json' \
    #     -H 'Authorization: token ${{ secrets.TOKEN_FOR_E2E_TESTS }}' \
    #     -d '{"event_type": "call"}'


# #IN TEST1
      # with code read and write
    - name: Repository Dispatch
      run: |
        curl -X POST https://api.github.com/repos/PAT-ORG/test1/dispatches \
        -H 'Accept: application/vnd.github+json' \
        -H 'Authorization: token ${{ secrets.TEST_TRIGGER_IN_PAT_ORG }}' \
        -d '{"event_type": "call"}'
        
    # - name: Trigger dispatch
    #   env:
    #     GH_TOKEN: ${{ secrets.TOKEN_FOR_E2E_TESTS }}
    #     REPO_OWNER: go-bazzinga
    #     REPO_NAME: hot-or-not-web-leptos-ssr-e2e-test
    #   run: |
    #     curl -X POST \
    #       -H "Accept: application/vnd.github+json" \
    #       -H "Authorization: Bearer $GH_TOKEN" \
    #       https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/dispatches \
    #       -d '{"event_type": "call"}'

        # trying using action v5
        # call another repo as post deploy action
    - name: Trigger a workflow in another repo
      uses: actions/github-script@v5
      with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'go-bazzinga',
              repo: 'hot-or-not-web-leptos-ssr-e2e-test',
              event_type: 'call',                    
              client_payload: { key: "value" }
            });
          github-token: ${{ secrets.TOKEN_FOR_E2E_TESTS }}
